default:
  method: "GET"
  route: "/"
  controller: "HomeController"
  action: "publicNotes"
  
newNote:
  method: "GET|POST"
  route: "/newNote"
  controller: "NotesController"
  action: "newNote"

privateNotes:
  method: "GET"
  route: "/privateNotes"
  controller: "NotesController"
  action: "privateNotes"

editNote:
  method: "GET|POST"
  route: "/editNote/[i:id]"
  controller: "NotesController"
  action: "editNote"

deleteNote:
  method: "GET"
  route: "/deleteNote/[i:id]"
  controller: "NotesController"
  action: "deleteNote"

editUser:
  method: "GET|POST"
  route: "/user/edit/[i:id]"
  controller: "AdminController"
  action: "editUser"

deleteUser:
  method: "GET"
  route: "/user/delete/[i:id]"
  controller: "AdminController"
  action: "deleteUser"

fourOFour:
  method: "GET"
  route: "/404"
  controller: "AuthController"
  action: "fourOFour"

login:
  method: "GET|POST"
  route: "/login"
  controller: "AuthController"
  action: "login"

logout:
  method: "GET|POST"
  route: "/logout"
  controller: "AuthController"
  action: "logout"

register:
  method: "GET|POST"
  route: "/register"
  controller: "AuthController"
  action: "register"

registerinfo:
  method: "GET"
  route: "/registerinfo"
  controller: "AuthController"
  action: "registerinfo"

verify:
  method: "GET"
  route: "/verify/[i:id]/[a:key]"
  controller: "AuthController"
  action: "verify"

retrieve:
  method: "GET|POST"
  route: "/retrieve/[i:id]/[a:key]"
  controller: "AuthController"
  action: "retrieve"

forgottenpw:
  method: "GET|POST"
  route: "/forgottenpw"
  controller: "AuthController"
  action: "forgottenpw"

pwinfo:
  method: "GET"
  route: "/pwinfo"
  controller: "AuthController"
  action: "pwinfo"

restricted:
  method: "GET"
  route: "/restricted"
  controller: "RestrictedController"
  action: "restricted"

profile:
  method: "GET"
  route: "/profile"
  controller: "ProfileController"
  action: "profile"

deleteAccount:
  method: "GET"
  route: "/deleteAccount/[i:id]"
  controller: "ProfileController"
  action: "deleteAccount"

dashboard:
  method: "GET"
  route: "/dashboard"
  controller: "AdminController"
  action: "dashboard"



