default:
  method: 'GET'
  route: '/'
  controller: 'Controllers\HomeController'
  action: 'publicNotes'
  
newNote:
  method: 'GET|POST'
  route: '/newNote'
  controller: 'Controllers\NotesController'
  action: 'newNote'

privateNotes:
  method: 'GET'
  route: '/privateNotes'
  controller: 'Controllers\NotesController'
  action: 'privateNotes'

editNote:
  method: 'GET|POST'
  route: '/editNote/[i:id]'
  controller: 'Controllers\NotesController'
  action: 'editNote'

deleteNote:
  method: 'GET'
  route: '/deleteNote/[i:id]'
  controller: 'Controllers\NotesController'
  action: 'deleteNote'

editUser:
  method: 'GET|POST'
  route: '/user/edit/[i:id]'
  controller: 'Controllers\AdminController'
  action: 'editUser'

deleteUser:
  method: 'GET'
  route: '/user/delete/[i:id]'
  controller: 'Controllers\AdminController'
  action: 'deleteUser'

fourOFour:
  method: 'GET'
  route: '/404'
  controller: 'Controllers\AuthController'
  action: 'fourOFour'

login:
  method: 'GET|POST'
  route: '/login'
  controller: 'Controllers\AuthController'
  action: 'login'

logout:
  method: 'GET|POST'
  route: '/logout'
  controller: 'Controllers\AuthController'
  action: 'logout'

register:
  method: 'GET|POST'
  route: '/register'
  controller: 'Controllers\AuthController'
  action: 'register'

registerinfo:
  method: 'GET'
  route: '/registerinfo'
  controller: 'Controllers\AuthController'
  action: 'registerinfo'

verify:
  method: 'GET'
  route: '/verify/[i:id]/[a:key]'
  controller: 'Controllers\AuthController'
  action: 'verify'

resetPassword:
  method: 'GET|POST'
  route: '/reset/[i:id]/[a:key]'
  controller: 'Controllers\AuthController'
  action: 'resetPassword'

forgottenpw:
  method: 'GET|POST'
  route: '/forgottenpw'
  controller: 'Controllers\AuthController'
  action: 'forgottenpw'

pwinfo:
  method: 'GET'
  route: '/pwinfo'
  controller: 'Controllers\AuthController'
  action: 'pwinfo'

restricted:
  method: 'GET'
  route: '/restricted'
  controller: 'Controllers\RestrictedController'
  action: 'restricted'

profile:
  method: 'GET|POST'
  route: '/profile'
  controller: 'Controllers\ProfileController'
  action: 'profile'

deleteAccount:
  method: 'GET'
  route: '/deleteAccount/[i:id]'
  controller: 'Controllers\ProfileController'
  action: 'deleteAccount'

dashboard:
  method: 'GET'
  route: '/dashboard'
  controller: 'Controllers\AdminController'
  action: 'dashboard'



